### ISSUE TITLE
Allow passing className to the slide-pane__content

### ISSUE THREAD

**Issue by zedtux** [DimitryDushkin/sliding-pane#47]
As of now, there's an option to pass some custom CSS classes to the `Modal` component, but I need to pass the bootstrap `d-flex` CSS class to the `div` with the CSS class `slide-pane__content` but I can't.

A `contentClassName` option should be added so that one can pass an additional class to the content `div`.

**Comment by sunviwo** [comment]
Yes, as for me I'm intending to eliminate the slide-page__content padding.

**Comment by sunviwo** [comment]
I eventually got it with css:
`
.slide-pane .slide-pane__content{
  padding: 0 !important;
}
`
Maybe you could try something like that.

**Comment by zedtux** [comment]
Why have you closed this issue @DimitryDushkin ?

**Comment by DimitryDushkin** [comment]
> Why have you closed this issue @DimitryDushkin ?

Hey! @sunviwo provided hint to solution, you didn't answered, so I decided it is not the case now.

You can do it like
```css
.slide-pane.my-class .slide-pane__content{ 
  padding: 0;
  /* all styles from d-flex or if you use CSS Modules/*
  composes d-flex;
}
```
For CSS Modules solution see https://github.com/css-modules/css-modules#composition
