### ISSUE TITLE
How to disable overlay ?

### ISSUE THREAD

**Issue by RiusmaX** [DimitryDushkin/sliding-pane#5]
Hi,

I'm trying to disable the content overlay, i just need tu use the panel as "menu" to edit the page content.

How can I do this ? I've tried to set the "overlayCustomClass" with "display: none" but it's hide the panel too :/

Edit: I've found an issue on react-modal if it can help : https://github.com/reactjs/react-modal/issues/259

Thanks for your work :)

**Comment by DimitryDushkin** [comment]
Just override it with CSS:
```css
.slide-pane__overlay.ReactModal__Overlay--after-open {
    background: transparent;
}
```
