### ISSUE TITLE
custom className defined in a css module is overridden

### ISSUE THREAD

**Issue by mquantin** [DimitryDushkin/sliding-pane#54]
when used with css modules, it seems that the custom className you offeris overrridden by your component styles. 
could you please help me with that? or explain me how you designed the use of that className prop?

<img width="430" alt="Capture d’écran 2021-03-15 à 12 08 47" src="https://user-images.githubusercontent.com/11961831/111144677-ae859000-8587-11eb-8b02-8082e6acd8c0.png">

**Comment by DimitryDushkin** [comment]
Try providing className property from your CSS modules export and override it in styles.

**Comment by mquantin** [comment]
Hey Dimitri, 
thanks for your reply. I didn't get what you proposed. Why is the issue closed? 

-> Has anyone tried to change the background color of the pane ? How do you managed to do it? 

I tried to override other properties in my custom className (e.g. text color). It works properly. 
As the problem is specific for background-color property,  I modified the issue name.

in my css module:
```css
.slidePane {
  background-color: papayawhip; /*nothing append, overriden by the .slide-pane class of the provided react-sliding-pane.css. */
  color: red; /*OK, this changes the text color*/
}
```

For now I modified directly the component in the provided react-sliding-pane.css. This is not a solution
